### PR TITLE
Add support for custom arguments.

### PR DESCRIPTION
**Pull request by teymour-aldridge**
This enables the passing of custom arguments to `cargo bloat` and `cargo tree`.

### CODE REVIEW

**Comment by teymour-aldridge** [comment]
I think that the error is caused because my PR (sensibly) does not have access to `secrets.GITHUB_TOKEN` and can therefore not add comments.

**Comment by orf** [comment]
Unfortunately you're right 😭. I'll merge this though, it looks good. Thanks for the contribution!

**Comment by teymour-aldridge** [comment]
@orf do you know if there is a way to safely run this on pull requests made to a repository?

**Comment by orf** [comment]
Yeah - we need to make the bloat be output to the build log and not via a comment. It really sucks to be honest, I think Github need to really improve their CI permission model.

**Comment by teymour-aldridge** [comment]
Ah. Not as fun having to browse through the build log, but I guess it’s the best solution :)

**Pull request merged**
